services:
  app:
    image: amneziawg
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "$AWG_SERVER_PORT:51820/udp"
    volumes:
      - ./awg:/etc/wireguard
      - /lib/modules:/lib/modules
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
